import type { SimulatorDashboardData } from '@/features/simulator/contracts'

const mockSimulatorDashboard: SimulatorDashboardData = {
  systems: [
    {
      id: 'growth',
      name: '성장 엔진',
      label: '유입 · 활성 · 잔존 루프',
      summary: '신규 유입과 잔존 캠페인이 동시에 흔들리고 있습니다.',
      danger: 82,
      requests: 4,
    },
    {
      id: 'trust',
      name: '신뢰 · 결제',
      label: '결제 회복 · 이탈 방어',
      summary: '환불 요청과 결제 실패가 같은 구간에서 증가 중입니다.',
      danger: 76,
      requests: 3,
    },
    {
      id: 'platform',
      name: '플랫폼 안정성',
      label: '지연 · 인시던트 대응',
      summary: '대시보드 기준으로 안정성 이슈가 재발하기 시작했습니다.',
      danger: 68,
      requests: 2,
    },
    {
      id: 'support',
      name: '핵심 고객 케어',
      label: 'VIP 코호트 · 응대 큐',
      summary: '핵심 고객층 불만과 장기 이탈 위험이 연결되고 있습니다.',
      danger: 71,
      requests: 5,
    },
  ],
  incidents: [
    {
      id: 'incident-growth-1',
      systemId: 'growth',
      title: '추천 루프 효율 급락',
      summary: '캠페인 유입은 유지되지만 7일 리텐션이 지난주 대비 6.8% 하락했습니다.',
      severity: 'critical',
      requester: '성장 리드',
      impact: '월 매출 추정 손실 -3.2%',
      window: '다음 48시간',
      request: '할인 남발 없이 반등할 수 있는 잔존 전략을 설계해 주세요.',
    },
    {
      id: 'incident-growth-2',
      systemId: 'growth',
      title: '튜토리얼 이탈 구간 식별',
      summary: '신규 사용자들이 3단계 온보딩에서 대량 이탈하고 있습니다.',
      severity: 'high',
      requester: '프로덕트 분석',
      impact: '활성 전환율 -4.1pt',
      window: '이번 주',
      request: '운영자가 즉시 적용할 수 있는 온보딩 보완 정책이 필요합니다.',
    },
    {
      id: 'incident-trust-1',
      systemId: 'trust',
      title: '결제 재시도 실패 급증',
      summary: '프리미엄 구독자에서 카드 재시도 실패가 집중적으로 증가하고 있습니다.',
      severity: 'critical',
      requester: '결제 운영',
      impact: 'MRR 방어 필요',
      window: '오늘 밤 정산 전',
      request: '환불 폭증을 막으면서도 VIP 고객 이탈을 억제해야 합니다.',
    },
    {
      id: 'incident-platform-1',
      systemId: 'platform',
      title: '배치 처리 지연',
      summary: '추천 결과 반영 배치가 27분 이상 밀리며 주요 화면 지표가 stale 상태입니다.',
      severity: 'high',
      requester: '인프라 온콜',
      impact: '실시간 의사결정 품질 저하',
      window: '현재 진행 중',
      request: '운영 정책을 보수적으로 바꾸고 알림 기준도 상향해야 합니다.',
    },
    {
      id: 'incident-support-1',
      systemId: 'support',
      title: 'VIP 불만 다발 구간',
      summary: '상위 5% 고객층에서 응답 지연과 서비스 방향 불만이 동시에 누적되고 있습니다.',
      severity: 'critical',
      requester: 'CS 매니저',
      impact: '핵심 계정 이탈 위험',
      window: '이번 분기 내',
      request: '직접적인 사과 메시지와 보상 정책을 엮은 대응안이 필요합니다.',
    },
    {
      id: 'incident-support-2',
      systemId: 'support',
      title: '운영 공지 톤 이슈',
      summary: '최근 공지 톤이 지나치게 방어적이라는 피드백이 쌓이고 있습니다.',
      severity: 'medium',
      requester: '커뮤니티 운영',
      impact: '브랜드 신뢰 저하 가능성',
      window: '다음 공지 전',
      request: '상황 설명과 관계 회복을 같이 잡을 수 있는 공지안이 필요합니다.',
    },
  ],
  predictionRows: [
    {
      id: 'pred-1',
      segment: 'High value / 30d cohort',
      churnRisk: '84%',
      urgency: 'Immediate',
      projectedLoss: '$182k',
      trigger: 'Payment retry failures + CS lag',
    },
    {
      id: 'pred-2',
      segment: 'New users / onboarding step 3',
      churnRisk: '71%',
      urgency: 'Today',
      projectedLoss: '$54k',
      trigger: 'Tutorial friction spike',
    },
    {
      id: 'pred-3',
      segment: 'Dormant returning cohort',
      churnRisk: '63%',
      urgency: 'This week',
      projectedLoss: '$39k',
      trigger: 'Offer fatigue + stale messaging',
    },
  ],
  initialPolicies: [
    {
      id: 'policy-1',
      title: 'VIP 방어 보호 구간',
      effect: '고위험 VIP 계정에는 가격/플랜 변경 노출을 72시간 중지',
      owner: '신뢰 · 결제',
      status: 'Armed',
      source: 'Preset',
    },
    {
      id: 'policy-2',
      title: '치명 이슈 우선 대응 큐',
      effect: '치명도 상위 이슈를 운영자 승인 전용 슬롯으로 승격',
      owner: '플랫폼 안정성',
      status: 'Queued',
      source: 'Preset',
    },
    {
      id: 'policy-3',
      title: '관계 회복 중심 메시지',
      effect: '리텐션 하락 구간에 보상 대신 관계 회복형 메시지를 우선 적용',
      owner: '성장 엔진',
      status: 'Draft',
      source: 'Preset',
    },
  ],
  initialMessages: [
    {
      id: 'message-1',
      role: 'operator',
      text: '전략 보조 에이전트가 준비되었습니다. 현재 상태 지표와 인시던트 로그를 함께 읽고 있습니다.',
    },
    {
      id: 'message-2',
      role: 'operator',
      text: '이번 달 우선순위는 성장, 결제 신뢰, 핵심 고객 보호입니다. 인시던트를 선택해 정책 초안을 구체화하세요.',
    },
  ],
  modelSignals: [
    { label: 'ROC-AUC', value: '0.91', detail: '정책 적용 전 기준 성능' },
    { label: 'Precision@Top-5%', value: '74%', detail: '상위 위험군 적중률' },
    { label: 'Lead Time', value: '3.4d', detail: '사전 탐지 여유' },
  ],
}

export function getMockSimulatorDashboard(): SimulatorDashboardData {
  return structuredClone(mockSimulatorDashboard)
}
